#!/bin/sh

dev=br-lan

# adding log function
dbg() {
    logger -t eqos -p user.info "$1"
	echo "$1"
}

stop_qos() {
	# delete tc rules
	tc qdisc del dev $dev root 2>/dev/null
	tc qdisc del dev $dev ingress 2>/dev/null
	tc qdisc del dev ${dev}-ifb root 2>/dev/null
	ip link del dev ${dev}-ifb 2>/dev/null
}

start_qos() {
	local dl=$1
	local up=$2
	# creating tc rules
	tc qdisc add dev $dev root handle 1: htb
	tc class add dev $dev parent 1: classid 1:1 htb rate ${dl}mbit

	ip link add dev ${dev}-ifb name ${dev}-ifb type ifb
	ip link set dev ${dev}-ifb up

	tc qdisc add dev ${dev}-ifb root handle 1: htb
	tc class add dev ${dev}-ifb parent 1: classid 1:1 htb rate ${up}mbit

	tc qdisc add dev $dev ingress
	tc filter add dev $dev parent ffff: protocol ip u32 match u32 0 0 flowid 1:1 action mirred egress redirect dev ${dev}-ifb
}

iptables_stop() {
	dbg "Cleaning up iptables rules"

	# delete eqos chains
	# delete calls
	iptables -t mangle -D FORWARD -j eqos
	ip6tables -t mangle -D FORWARD -j eqos
	ebtables -t nat -D POSTROUTING -j eqos
	# delete chains
	iptables -t mangle -F eqos
	ip6tables -t mangle -F eqos
	ebtables -t nat -F eqos
	iptables -t mangle -X eqos
	ip6tables -t mangle -X eqos
	ebtables -t nat -X eqos

	# disable HQoS
	echo 0 > /sys/kernel/debug/hnat/qos_toggle

	# delete firewall trigger for eqos
	sed -i '/\/etc\/init.d\/eqos start/d' /etc/firewall.user

	# remove all MARK marks set by eqos
	iptables -t mangle -D FORWARD -i br-lan -j MARK --set-mark 0
	iptables -t mangle -D FORWARD -o br-lan -j MARK --set-mark 0
	ip6tables -t mangle -D FORWARD -i br-lan -j MARK --set-mark 0
	ip6tables -t mangle -D FORWARD -o br-lan -j MARK --set-mark 0

	# disable HNat DSCP support
	# echo "10 0" > /sys/kernel/debug/hnat/hnat_setting

	# restore hnat band rate
	echo "11 30" >/sys/kernel/debug/hnat/hnat_setting
	uci -q set "turboacc.config.fastpath_mh_eth_hnat_bind_rate"="30"
	uci -q commit "turboacc"

	# Reset HQoS queue parameters
	## downlink queues
	for i in $(seq 0 31); do
		echo 0 0 0 0 0 4 4 > /sys/kernel/debug/hnat/qdma_txq$i
	done
	## uplink queues
	for i in $(seq 32 63); do
		echo 1 0 0 0 0 4 4 > /sys/kernel/debug/hnat/qdma_txq$i
	done

	# reset HQoS scheduler parameters
	echo 0 wrr 25000000 > /sys/kernel/debug/hnat/qdma_sch0
	echo 0 wrr 25000000 > /sys/kernel/debug/hnat/qdma_sch1
	echo 0 wrr 25000000 > /sys/kernel/debug/hnat/qdma_sch2
	echo 0 wrr 25000000 > /sys/kernel/debug/hnat/qdma_sch3
}

iptables_start_prepare() {
	dbg "Prepare iptables structures"
	# remove any existing MARK rules to avoid duplicates
	iptables -t mangle -D FORWARD -i br-lan -j MARK --set-mark 0
	iptables -t mangle -D FORWARD -o br-lan -j MARK --set-mark 0
	iptables -t mangle -A FORWARD -i br-lan -j MARK --set-mark 0
	iptables -t mangle -A FORWARD -o br-lan -j MARK --set-mark 0
	ip6tables -t mangle -D FORWARD -i br-lan -j MARK --set-mark 0
	ip6tables -t mangle -D FORWARD -o br-lan -j MARK --set-mark 0
	ip6tables -t mangle -A FORWARD -i br-lan -j MARK --set-mark 0
	ip6tables -t mangle -A FORWARD -o br-lan -j MARK --set-mark 0
}

iptables_start_inital() {
	dbg "Initializing iptables structures"

	# create eqos chains
	ebtables -t nat -N eqos
	ebtables -t nat -F eqos
	iptables -t mangle -N eqos
	iptables -t mangle -F eqos

	# attach calls
	iptables -t mangle -D FORWARD -j eqos
	iptables -t mangle -A FORWARD -j eqos || dbg "ERROR: Failed to attach eqos chain to FORWARD"
	ebtables -t nat -D POSTROUTING -j eqos
	ebtables -t nat -A POSTROUTING -j eqos || dbg "ERROR: Failed to attach eqos chain to POSTROUTING"

	# enable HQoS
	echo 1 > /sys/kernel/debug/hnat/qos_toggle

	# set HQoS scheduler parameters to default(disable rate limiting,WRR mode,this two schedulers are used for general traffic)
	echo 0 wrr 25000000 > /sys/kernel/debug/hnat/qdma_sch0
	echo 0 wrr 25000000 > /sys/kernel/debug/hnat/qdma_sch1

	# binging HQoS queues to default(disable rate limiting)
	echo 0 0 0 0 0 0 4 > /sys/kernel/debug/hnat/qdma_txq0
	echo 1 0 0 0 0 0 4 > /sys/kernel/debug/hnat/qdma_txq63

	# set hnat bind rate to 5pps to let more packets go through hqos
	echo "11 5" >/sys/kernel/debug/hnat/hnat_setting
	uci -q set "turboacc.config.fastpath_mh_eth_hnat_bind_rate"="5"
	uci -q commit "turboacc"

	# add firewall trigger for eqos if not existing
	sed -i '/\/etc\/init.d\/eqos start/d' /etc/firewall.user
	echo "/etc/init.d/eqos start" >> /etc/firewall.user

	# enable HNat DSCP support
	# echo "10 1" > /sys/kernel/debug/hnat/hnat_setting
}


case "$1" in
	"stop")
		stop_qos
		iptables_stop
		dbg "Stopping QoS subsystem"
	;;
	"start")
		dbg "Initializing QoS subsystem - DL: $2Mbps, UL: $3Mbps"
		stop_qos
		iptables_start_prepare
		start_qos $2 $3
		iptables_start_inital $2 $3
		# set HQoS scheduler parameters for uplink and downlink
		# uplink scheduler
		echo 1 wrr $(($3*1000)) > /sys/kernel/debug/hnat/qdma_sch2
		# downlink scheduler
		echo 1 wrr $(($2*1000)) > /sys/kernel/debug/hnat/qdma_sch3
	;;
	"add")
		ip="$2"
		dl="$3"
		up="$4"
		id="$5"
		idpair=$((id+32))
		macaddr="$6"
		interface="$7"
		cnt=$(tc class show dev $dev | wc -l)
		dbg "Adding Devices QoS rule: IP=$2, DL=$3Kbps, UL=$4Kbps, ID=$5, MAC=$6, IF=$7"

		# HQoS queue max number is 32
		if [ $id -lt 32 ]; then
			# delete existing rules
			iptables -t mangle -D eqos -m mac --mac-source $macaddr -j MARK --set-mark $((${id} \<\< 16))
			ip6tables -t mangle -D eqos -m mac --mac-source $macaddr -j MARK --set-mark $((${id} \<\< 16))
			ebtables -t nat -D eqos -d $macaddr -j mark --mark-set $((${idpair} \<\< 16))

			# create upload rule
			if [ $up -ne 0 ]; then
				echo 3 0 0 1 ${up} 4 1 > /sys/kernel/debug/hnat/qdma_txq$((${id} \<\< 16))
				iptables -t mangle -A eqos -m mac --mac-source $macaddr -j MARK --set-mark $((${id} \<\< 16))
				ip6tables -t mangle -A eqos -m mac --mac-source $macaddr -j MARK --set-mark $((${id} \<\< 16))
			fi

			# create download rule
			if [ $dl -ne 0 ]; then
				echo 2 0 0 1 ${dl} 4 1 > /sys/kernel/debug/hnat/qdma_txq$((${idpair} \<\< 16))
				ebtables -t nat -A eqos -d $macaddr -j mark --mark-set $((${idpair} \<\< 16))
			fi
		else
			# greater than queue 32 use traditional eqos rules
			iptables -t mangle -D eqos -s $ip -j MARK --set-mark 0x99
			iptables -t mangle -D eqos -d $ip -j MARK --set-mark 0x99

			if [ $up -ne 0 ]; then
				iptables -t mangle -A eqos -s $ip -j MARK --set-mark 0x99
			fi

			if [ $dl -ne 0 ]; then
				iptables -t mangle -A eqos -d $ip -j MARK --set-mark 0x99
			fi
		fi

		# set tc class for ip greater than 32
		if [ $id -gt 31 ]; then
			tc class add dev $dev parent 1:1 classid 1:1$cnt htb rate ${dl}kbit ceil ${dl}kbit
			tc filter add dev $dev parent 1:0 protocol ip u32 match ip dst $ip flowid 1:1$cnt
			tc class add dev ${dev}-ifb parent 1:1 classid 1:1$cnt htb rate ${up}kbit ceil ${up}kbit
			tc filter add dev ${dev}-ifb parent 1:0 protocol ip u32 match ip src $ip flowid 1:1$cnt
		fi

		# multi-interface load balancing
		if [ $interface ]; then
			iptables -t mangle -D PREROUTING -m mac --mac-source $macaddr -m conntrack --ctstate NEW -j MARK --set-mark 2"$interface" -m comment --comment "EQoS_DEVICE_$macaddr"
			iptables -t mangle -A PREROUTING -m mac --mac-source $macaddr -m conntrack --ctstate NEW -j MARK --set-mark 2"$interface" -m comment --comment "EQoS_DEVICE_$macaddr"
			iptables -t mangle -D PREROUTING -i br-lan -m conntrack --ctstate ESTABLISHED,RELATED -j CONNMARK --restore-mark -m comment --comment "EQoS_DEVICE_$macaddr"
			iptables -t mangle -A PREROUTING -i br-lan -m conntrack --ctstate ESTABLISHED,RELATED -j CONNMARK --restore-mark -m comment --comment "EQoS_DEVICE_$macaddr"
		fi
	;;
	*)
		echo "Usage: $0 <command> [options]"
		echo "Commands:"
		echo " start dl_rate up_rate  #Total bandwidth (Mbit/s)"
		echo " stop"
		echo " add ip dl_rate up_rate #Limiting the bandwidth of a single IP (kbit/s)"
		echo "Example:"
		echo " $0 start 30 20 # Total bandwidth: down 30Mbit/s up 20Mbit/s"
		echo " $0 add 192.168.22.12 10 2  # down 10kbit/s up 2kbit/s"
	;;
esac
