#!/bin/sh

dev=br-lan

# 添加日志函数
dbg() {
    logger -t eqos -p user.info "$1"
	echo "$1"
}

stop_qos() {
	# 删除tc规则
	tc qdisc del dev $dev root 2>/dev/null
	tc qdisc del dev $dev ingress 2>/dev/null
	tc qdisc del dev ${dev}-ifb root 2>/dev/null
	ip link del dev ${dev}-ifb 2>/dev/null
}

start_qos() {
	local dl=$1
	local up=$2
	# 创建的tc规则
	tc qdisc add dev $dev root handle 1: htb
	tc class add dev $dev parent 1: classid 1:1 htb rate ${dl}mbit

	ip link add dev ${dev}-ifb name ${dev}-ifb type ifb
	ip link set dev ${dev}-ifb up

	tc qdisc add dev ${dev}-ifb root handle 1: htb
	tc class add dev ${dev}-ifb parent 1: classid 1:1 htb rate ${up}mbit

	tc qdisc add dev $dev ingress
	tc filter add dev $dev parent ffff: protocol ip u32 match u32 0 0 flowid 1:1 action mirred egress redirect dev ${dev}-ifb
}

iptables_stop() {
	dbg "Cleaning up iptables rules"

	# 删除eqos链
	# 删除调用
	iptables -t mangle -D FORWARD -j eqos
	ip6tables -t mangle -D FORWARD -j eqos
	ebtables -t nat -D POSTROUTING -j eqos
	# 删除链
	iptables -t mangle -F eqos
	ip6tables -t mangle -F eqos
	ebtables -t nat -F eqos
	iptables -t mangle -X eqos
	ip6tables -t mangle -X eqos
	ebtables -t nat -X eqos

	# 关闭HQoS
	echo 0 > /sys/kernel/debug/hnat/qos_toggle

	# 删除firewall触发eqos的指令
	sed -i '/\/etc\/init.d\/eqos start/d' /etc/firewall.user

	# 设置所有删除设置的DSCP标记
	iptables -t mangle -D FORWARD -i br-lan -j DSCP --set-dscp 0
	iptables -t mangle -D FORWARD -o br-lan -j DSCP --set-dscp 0
	ip6tables -t mangle -D FORWARD -i br-lan -j DSCP --set-dscp 0
	ip6tables -t mangle -D FORWARD -o br-lan -j DSCP --set-dscp 0

	# 关闭HNat的DSCP支持
	echo "10 0" > /sys/kernel/debug/hnat/hnat_setting

	# 回调hnat band rate
	echo "11 30" >/sys/kernel/debug/hnat/hnat_setting
	uci -q set "turboacc.config.fastpath_mh_eth_hnat_bind_rate"="30"
	uci -q commit "turboacc"

	# 清空HQoS队列参数
	## 设备下行队列
	for i in $(seq 0 31); do
		echo 0 0 0 0 0 4 4 > /sys/kernel/debug/hnat/qdma_txq$i
	done
	## 设备上行队列
	for i in $(seq 32 63); do
		echo 1 0 0 0 0 4 4 > /sys/kernel/debug/hnat/qdma_txq$i
	done

	# 清空HQoS调度器参数
	echo 0 wrr 25000000 > /sys/kernel/debug/hnat/qdma_sch0
	echo 0 wrr 25000000 > /sys/kernel/debug/hnat/qdma_sch1
	echo 0 wrr 25000000 > /sys/kernel/debug/hnat/qdma_sch2
	echo 0 wrr 25000000 > /sys/kernel/debug/hnat/qdma_sch3
}

iptables_start_prepare() {
	dbg "Prepare iptables structures"
	# 清除所有现存的DSCP标记
	iptables -t mangle -D FORWARD -i br-lan -j DSCP --set-dscp 0
	iptables -t mangle -D FORWARD -o br-lan -j DSCP --set-dscp 0
	iptables -t mangle -A FORWARD -i br-lan -j DSCP --set-dscp 0
	iptables -t mangle -A FORWARD -o br-lan -j DSCP --set-dscp 0
	ip6tables -t mangle -D FORWARD -i br-lan -j DSCP --set-dscp 0
	ip6tables -t mangle -D FORWARD -o br-lan -j DSCP --set-dscp 0
	ip6tables -t mangle -A FORWARD -i br-lan -j DSCP --set-dscp 0
	ip6tables -t mangle -A FORWARD -o br-lan -j DSCP --set-dscp 0
}

iptables_start_inital() {
	dbg "Initializing iptables structures"

	# 创建并清空eqos链
	ebtables -t nat -N eqos
	ebtables -t nat -F eqos
	iptables -t mangle -N eqos
	iptables -t mangle -F eqos

	# 调用eqos链
	iptables -t mangle -D FORWARD -j eqos
	iptables -t mangle -A FORWARD -j eqos || dbg "ERROR: Failed to attach eqos chain to FORWARD"
	ebtables -t nat -D POSTROUTING -j eqos
	ebtables -t nat -A POSTROUTING -j eqos || dbg "ERROR: Failed to attach eqos chain to POSTROUTING"

	# 开启HQoS
	echo 1 > /sys/kernel/debug/hnat/qos_toggle

	# 设置0和1HQoS调度器参数（不限速2.5G,WRR策略）
	echo 1 wrr $(($2*1000)) > /sys/kernel/debug/hnat/qdma_sch0
	echo 1 wrr $(($1*1000)) > /sys/kernel/debug/hnat/qdma_sch1

	# 绑定特定HQoS队列参数到调度器0和1(绑定到0和1调度器,不启用最大最小限速,权重0等价于最高权重)
	echo 0 0 0 0 0 0 0 > /sys/kernel/debug/hnat/qdma_txq0
	echo 1 0 0 0 0 0 0 > /sys/kernel/debug/hnat/qdma_txq32

	# 下调HNat band rate
	echo "11 5" >/sys/kernel/debug/hnat/hnat_setting
	uci -q set "turboacc.config.fastpath_mh_eth_hnat_bind_rate"="5"
	uci -q commit "turboacc"

	# 添加firewall触发eqos的指令
	sed -i '/\/etc\/init.d\/eqos start/d' /etc/firewall.user
	echo "/etc/init.d/eqos start" >> /etc/firewall.user

	# 开启HNat DSCP支持
	echo "10 1" > /sys/kernel/debug/hnat/hnat_setting
}


case "$1" in
	"stop")
		stop_qos
		iptables_stop
		dbg "Stopping QoS subsystem"
	;;
	"start")
		dbg "Initializing QoS subsystem - DL: $2Mbps, UL: $3Mbps"
		stop_qos
		iptables_start_prepare
		start_qos $2 $3
		iptables_start_inital $2 $3
		# 设置用于QoS的调度器参数
		echo 1 wrr $(($3*1000)) > /sys/kernel/debug/hnat/qdma_sch2
		echo 1 wrr $(($2*1000)) > /sys/kernel/debug/hnat/qdma_sch3
	;;
	"add")
		ip="$2"
		dl="$3"
		up="$4"
		id="$5"
		idpair=$((id+32))
		macaddr="$6"
		interface="$7"
		cnt=$(tc class show dev $dev | wc -l)
		dbg "Adding Devices QoS rule: IP=$2, DL=$3Kbps, UL=$4Kbps, ID=$5, MAC=$6, IF=$7"

		# 硬件hqos队列的最大长度为32
		if [ $id -lt 32 ]; then
			# 删除现有规则
			iptables -t mangle -D eqos -m mac --mac-source $macaddr -j DSCP --set-dscp ${id}
			ip6tables -t mangle -D eqos -m mac --mac-source $macaddr -j DSCP --set-dscp ${id}
			ebtables -t nat -D eqos -d $macaddr -j mark --mark-set ${idpair}

			# 创建上传规则
			if [ $up -ne 0 ]; then
				echo 2 0 0 1 ${up} 4 1 > /sys/kernel/debug/hnat/qdma_txq${id}
				iptables -t mangle -A eqos -m mac --mac-source $macaddr -j DSCP --set-dscp ${id}
				ip6tables -t mangle -A eqos -m mac --mac-source $macaddr -j DSCP --set-dscp ${id}
			fi

			# 创建下载规则
			if [ $dl -ne 0 ]; then
				echo 3 0 0 1 ${dl} 4 1 > /sys/kernel/debug/hnat/qdma_txq${idpair}
				ebtables -t nat -A eqos -d $macaddr -j mark --mark-set ${idpair}
			fi
		else
			# 大于队列32则使用传统eqos的规则
			iptables -t mangle -D eqos -s $ip -j MARK --set-mark 0x99
			iptables -t mangle -D eqos -d $ip -j MARK --set-mark 0x99

			if [ $up -ne 0 ]; then
				iptables -t mangle -A eqos -s $ip -j MARK --set-mark 0x99
			fi

			if [ $dl -ne 0 ]; then
				iptables -t mangle -A eqos -d $ip -j MARK --set-mark 0x99
			fi
		fi

		# 大于队列32则使用传统eqos的规则
		if [ $id -gt 31 ]; then
			tc class add dev $dev parent 1:1 classid 1:1$cnt htb rate ${dl}kbit ceil ${dl}kbit
			tc filter add dev $dev parent 1:0 protocol ip u32 match ip dst $ip flowid 1:1$cnt
			tc class add dev ${dev}-ifb parent 1:1 classid 1:1$cnt htb rate ${up}kbit ceil ${up}kbit
			tc filter add dev ${dev}-ifb parent 1:0 protocol ip u32 match ip src $ip flowid 1:1$cnt
		fi

		# 多接口负载均衡
		if [ $interface ]; then
			iptables -t mangle -D PREROUTING -m mac --mac-source $macaddr -m conntrack --ctstate NEW -j MARK --set-mark 2"$interface" -m comment --comment "EQoS_DEVICE_$macaddr"
			iptables -t mangle -A PREROUTING -m mac --mac-source $macaddr -m conntrack --ctstate NEW -j MARK --set-mark 2"$interface" -m comment --comment "EQoS_DEVICE_$macaddr"
			iptables -t mangle -D PREROUTING -i br-lan -m conntrack --ctstate ESTABLISHED,RELATED -j CONNMARK --restore-mark -m comment --comment "EQoS_DEVICE_$macaddr"
			iptables -t mangle -A PREROUTING -i br-lan -m conntrack --ctstate ESTABLISHED,RELATED -j CONNMARK --restore-mark -m comment --comment "EQoS_DEVICE_$macaddr"
		fi
	;;
	*)
		echo "Usage: $0 <command> [options]"
		echo "Commands:"
		echo " start dl_rate up_rate  #Total bandwidth (Mbit/s)"
		echo " stop"
		echo " add ip dl_rate up_rate #Limiting the bandwidth of a single IP (kbit/s)"
		echo "Example:"
		echo " $0 start 30 20 # Total bandwidth: down 30Mbit/s up 20Mbit/s"
		echo " $0 add 192.168.22.12 10 2  # down 10kbit/s up 2kbit/s"
	;;
esac
